# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: stavd
app: get-random-videos
service: myfavchef

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
  
    
functions:
  randomVideo:
    handler: handler.randomVideo
    events:
      - http:
          path: get-random-video
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - ${env:SECURITY_GROUP_ID}
      subnetIds:
        - ${env:SUBNET_ID1}
        - ${env:SUBNET_ID2}
        - ${env:SUBNET_ID3}
        - ${env:SUBNET_ID4}
        - ${env:SUBNET_ID5}
        - ${env:SUBNET_ID6}
        
resources:
  Resources:
    VideoRDSInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: ${self:provider.environment.DB_NAME}
        Engine: mysql  
        MasterUsername: ${self:provider.environment.DB_USER}
        MasterUserPassword: ${self:provider.environment.DB_PASSWORD}
        AllocatedStorage: 20
        DBInstanceClass: db.t3.micro  # Choose appropriate instance type
        PubliclyAccessible: false  # Set to true if you need to access from outside VPC
        Tags:
          - Key: Name
            Value: VideoRDSInstance
        VPCSecurityGroups:
          - ${env:SECURITY_GROUP_ID}  
    
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

