# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: stavd
app: get-random-videos
service: myfavchef

provider:
  name: aws
  runtime: nodejs20.x

functions:
  randomVideo:
    handler: handler.randomVideo
    events:
      - http:
          path: get-random-video
          method: get
          cors: true

package:
  include:
    - uniqueVideos.json
